name: SavageSkyblock
main: net.prosavage.savageskyblock.SavageSkyblock
version: 1.0-SNAPSHOT
api-version: 1.13
description: The ultimate skyblock plugin
author: ProSavage
commands:
  skyblock:
    description: Main skyblock command.
    aliases: [is, island]